export interface SoundtrackItem {
  title: string;
  file: any;
  duration?: string;
}

export interface ContentItem {
  id: string;
  nombre: string;
  descripcion: string;
  fondo: any;
  logo: any;
  capitulos: number;
  fuente: any[]; 
  nombresEpisodios: string[];
  fechaEstreno: string;
  puntuacion: number;
  categoria?: string[];
  verticalbanner: any;
  soundtracks?: SoundtrackItem[];
}

export const ContentData: ContentItem[] = [
  {
    id: 'Beck: Mongolian Chop Squad',
    nombre: 'Beck: Mongolian Chop Squad',
    descripcion: 'Beck: Mongolian Chop Squad es un anime que sigue la historia de Yukio "Koyuki" Tanaka, un adolescente que descubre su pasión por la música y se une a una banda llamada Beck. A medida que Koyuki y sus amigos luchan por alcanzar el éxito en la industria musical, enfrentan desafíos personales y profesionales, explorando temas de amistad, perseverancia y el poder transformador de la música.',
    fondo: require('../assets/images/beck_bg.jpg'),
    logo: require('../assets/images/beck_logo.png'),
    capitulos: 26,
    fuente: [
  "https://mega.nz/embed/UeMQlRoR#EwlxBorqdNokJXjM0G2JsHlU9dSa9YwZhjnAG2ArWe0",
  "https://mega.nz/embed/YCUjCYCQ#30OGp2gc0pO5oAzhVE5PnEcuDTSvhmo2OB7t25mI0b4",
  "https://mega.nz/embed/ZHsUgAwC#U3LyAl9O84bl_Ve4B_vbwyDQirr21uA22e6SuHhVa4Q",
  "https://mega.nz/embed/9f8RFTCB#MVTyzGVCLr05Vr_KVVy1QnpOFBKVG7NMqkXprDVKJo8",
  "https://mega.nz/embed/kH8hWLIb#rjzRF9Rcje_OXtSfn7UkwWufxoG5swFkjQqHgtLB6Xg",
  "https://mega.nz/embed/wPd3iTbS#RB1wpl8AjjpfZdL2xv38tLfkCb32EL2QvCMhptVGel4",
  "https://mega.nz/embed/gCs3AKYS#q7SX7XX_3JCQWmAg0aIBl837o-BaXUYUTv6WAKGn9vs",
  "https://mega.nz/embed/BKlQ2LiI#xx4bWEDsMu5WkmV979OouGGAomBfD_bmiTKywJUX6kY",
  "https://mega.nz/embed/1DlUgQDa#Us0IIeVyIM9gsoCdxKvbLDKu-JzrOLOO6v-BCxmlSFQ",
  "https://mega.nz/embed/BHNAmJgC#HwiWl9ylp3d-Iy8-LmxJ0KXLSDHV9KB9KU8ohsXbx-8",
  "https://mega.nz/embed/JaklwB5Z#eiozQWqedA5u3IW1mnxTGwWJxWAFHVnhWlKzA9iNWyQ",
  "https://mega.nz/embed/Zbs1xYiI#QVOFwKO2RJBMcfphtCSgGJ5rWnbzbsQHFjWfWA0vayw",
  "https://mega.nz/embed/5Ts3jIRR#pSS3ni2xyOfIlBDKFp7PcLIZEuwH0R2YRbEK2gW8jSQ",
  "https://mega.nz/embed/1HcGXBJa#0JCGpU9biGfqRw_rRJiX94r1ysR-8APX0ydFJPMeUzg",
  "https://mega.nz/embed/4W0U2TSZ#KcmlcodN8m1q15fTKXV-vrAA9SpXSY69D-TWU8xWris",
  "https://mega.nz/embed/gPcyxYzJ#W6UKRL4RKIe0oNyOPrX5EU55YrhnKHmgjTcy7mUzJW0",
  "https://mega.nz/embed/ZaFlnbiR#q9QmS8asUZwQFPoSzB_DDcZ4O2ttouANcr203sW7eWA",
  "https://mega.nz/embed/gadzESbY#F5KIBN725G90efvg2hFrtFmQmYR4RTh-NYI_lGGDEGw",
  "https://mega.nz/embed/sT8ikSwQ#oZIMeYC0qmq9d7LVqDV-Gu1rQ1AErCQwMBLXyNTGV0I",
  "https://mega.nz/embed/pb0HkJKT#Fv318aTpT7MmqXVrgc7L3Q7nbyYSngezjIS549-GEok",
  "https://mega.nz/embed/0Kcx1YCQ#IiRXePMLImGJ76ZM0XeHxARvrRH8kFUsHMKBNT22hLY",
  "https://mega.nz/embed/cfsllaJY#J0kH_1Nej2s1mTyDdqtyO05ZW7tnSbDGx3-c_wZw-FU",
  "https://mega.nz/embed/BT9HwZCD#Np3q67k593LLofozxzpql1YX7iDW12ShcqCSLUIrAdI",
  "https://mega.nz/embed/EHU2lR5R#oB5cGeOAEvvDPEN83kpGLUKBbXS3o68x3Ma1QmEv_Ec",
  "https://mega.nz/embed/9StmxCiB#Oawy_vpICcmKz1rh8CpLDGOV4JjFbsnd-y19v4_FC1U",
  "https://mega.nz/embed/ETcgEaDB#_Zkmt5eCDUjcfcLQsqRFL10qZTZqdhovnghh0EZHVEk"
],
    nombresEpisodios: [
        "1. El escenario de un chaval de 14 años",
        "2. Sala de conciertos",
        "3. Moon on the water",
        "4. Rasguea la guitarra",
        "5. Beck",
        "6. Hyodo y la Jaguar",
        "7. Lucille",
        "8. Comunicado del instituto",
        "9. Víspera del concierto",
        "10. Face",
        "11. Vacaciones de verano",
        "12. Concierto secreto",
        "13. Ciel Bleu",
        "14. Sueño",
        "15. Vuelta al insti",
        "16. Indies",
        "17. Tres días",
        "18. Leon Sykes",
        "19. Blues",
        "20. Greatful sound",
        "21. Componer música",
        "22. La víspera del festival",
        "23. El festival",
        "24. El tercer escenario",
        "25. Slip Out",
        "26. América"
    ],
    fechaEstreno: '2004-10-07',
    puntuacion: 8.9,
    categoria: ['Anime', 'Serie'],
    verticalbanner: require('../assets/images/beckverticalbanner.png'),
    // Temporalmente comentado - archivos de música removidos
    /* soundtracks: [
      { title: "Brainstorm", file: require('../assets/Music/Beck/Brainstorm.mp3'), duration: "4:12" },
      { title: "By Her", file: require('../assets/Music/Beck/By Her.mp3'), duration: "3:47" },
      { title: "Face (Acoustic)", file: require('../assets/Music/Beck/Face [Acoustic].mp3'), duration: "2:58" },
      { title: "Face", file: require('../assets/Music/Beck/Face.mp3'), duration: "3:21" },
      { title: "Follow Me (Live)", file: require('../assets/Music/Beck/Follow Me [Live].mp3'), duration: "4:33" },
      { title: "I've Got a Feeling (Live)", file: require('../assets/Music/Beck/I\'ve Got a Feeling [Live].mp3'), duration: "3:15" },
      { title: "In the Darkness", file: require('../assets/Music/Beck/In the Darkness.mp3'), duration: "3:44" },
      { title: "Journey", file: require('../assets/Music/Beck/Journey.mp3'), duration: "4:01" },
      { title: "Koyuki's 1st Practice", file: require('../assets/Music/Beck/Koyuki\'s 1st Practice.mp3'), duration: "1:23" },
      { title: "Koyuki's 2nd Practice", file: require('../assets/Music/Beck/Koyuki\'s 2nd Practice.mp3'), duration: "1:45" },
      { title: "Koyuki's 3rd Practice", file: require('../assets/Music/Beck/Koyuki\'s 3rd Practice.mp3'), duration: "2:11" },
      { title: "Like a Foojin", file: require('../assets/Music/Beck/Like a Foojin.mp3'), duration: "3:56" },
      { title: "Lost Melody", file: require('../assets/Music/Beck/Lost Melody.mp3'), duration: "4:18" },
      { title: "Moon on the Water (Dying Breed)", file: require('../assets/Music/Beck/Moon on the Water [Dying Breed].mp3'), duration: "4:22" },
      { title: "Moon on the Water (Pool)", file: require('../assets/Music/Beck/Moon on the Water [Pool].mp3'), duration: "4:07" },
      { title: "Moon on the Water", file: require('../assets/Music/Beck/Moon on the Water.mp3'), duration: "3:53" },
      { title: "My World Down", file: require('../assets/Music/Beck/My World Down.mp3'), duration: "3:29" },
      { title: "Ryuusuke's Warmup", file: require('../assets/Music/Beck/Ryuusuke\'s Warmup.mp3'), duration: "1:12" },
      { title: "Slip Out (Practice)", file: require('../assets/Music/Beck/Slip Out [Practice].mp3'), duration: "2:35" },
      { title: "Slip Out", file: require('../assets/Music/Beck/Slip out.mp3'), duration: "3:48" },
      { title: "Sly", file: require('../assets/Music/Beck/Sly.mp3'), duration: "3:31" },
      { title: "Spice of Life", file: require('../assets/Music/Beck/Spice of Life.mp3'), duration: "4:05" },
      { title: "Takano's Demo", file: require('../assets/Music/Beck/Takano\'s Demo.mp3'), duration: "2:43" }
    ], */
  },
  {
    id: 'The Last of Us',
    nombre: 'The Last of Us',
    descripcion: 'The Last of Us sigue a Joel, un hombre endurecido por la pérdida, que debe escoltar a Ellie, una joven inmune a una infección que ha devastado al mundo. Juntos cruzan un Estados Unidos postapocalíptico lleno de peligros humanos e infectados, enfrentando desafíos que pondrán a prueba su vínculo, su moral y su voluntad de sobrevivir.',
    fondo: require('../assets/images/tloutemp1.webp'),
    logo: require('../assets/images/The_Last_of_Us_logo.png'),
    capitulos: 9,
    fuente: [
      "https://mega.nz/embed/XcNmARSb#KOZC9pDtRpInPN7XqA9YRjfJSq7aWfrQUTVViyLH5M0",
      "https://mega.nz/embed/6cUiQYaZ#njRVc85KH6t7K1bm4WgF3gFiOID2hVa99YD_3W1f4dc",
      "https://mega.nz/embed/jcFDjLxI#KFUUe_HcGxhaCQBesmkAC3t3MkuPeVGpS1GlugDvLgA",
      "https://mega.nz/embed/ScVghDDb#Es-SUENs5c2svanMPF8zTzaxj2XhPJvrXFYr6LiSnmY",
      "https://mega.nz/embed/TJEA0BqQ#s9u9njTRmjmcHbp3i3EYihCRWsvYODF0roUHrQd-EKk",
      "https://mega.nz/embed/CVcG2SAJ#G2Cu-U8iYf1LSKFp4-cxosoTPpuy5khXCLtI55Mv6Us",
      "https://mega.nz/embed/2EEQQaLQ#dtMvf6-WUYqwA-WwlWb6eoVpQuzil9aV3AXc1lRcMlQ",
      "https://mega.nz/embed/GN9hxQAT#GK4NOYoUW2vJDVaf0G1G4tVKnD2tDja1Mgw63bPJSYo",
      "https://mega.nz/embed/mJ8BkQrL#EIbGHu0rGr5zq4NpNtNxBbLOqUd7QymG7pV9rBts570"
    ],
    nombresEpisodios: [
        "1. Cuando te pierdes en la oscuridad",
        "2. Infectados",
        "3. Mucho, mucho tiempo",
        "4. Por favor, toma mi mano",
        "5. Resistir y sobrevivir",
        "6. Familia",
        "7. Lo que dejamos atrás",
        "8. En nuestras horas más bajas",
        "9. Busca la luz"
    ],
    fechaEstreno: '2022',
    puntuacion: 9.5,
    categoria: ['Serie'],
    verticalbanner: require('../assets/images/tlouverticalbanner.jpg')
  },
  {
    id: 'Monster',
    nombre: 'Monster',
    descripcion: 'El doctor Kenzo Tenma es un prometedor neurocirujano japonés que ejerce en el Eisler Memorial Hospital de Dusseldorf. Lo tiene todo en la vida; un trabajo que le apasiona y en el que demuestra una habilidad increíble, y una novia rica y guapa. Sin embargo, un día decide ignorar una orden de su superior y salva a un niño desconocido en lugar de la vida del alcalde de la ciudad.',
    fondo: require('../assets/images/Monster.png'),
    logo: require('../assets/images/Monsterbanner.png'),
    capitulos: 74,
    fuente: [
        "https://mega.nz/embed/OfgE3Azb#AEsgFwDBLFOQAz-trXRumQC_zwsAjuBmkB1vFa1lbIg",
        "https://mega.nz/embed/uCgU2IZQ#ABZkNgAN7RXj0QRNhrR5eQCdStgAMWll4_qJZIaCfh0",
        "https://mega.nz/embed/2LBxzALB#AGf1KgCAxIvAlzYFu4zrdABMv3YAuT-BwNBh07tr2kU",
        "https://mega.nz/embed/eLYUDDDK#AKUz6gCTzvW0eKh4JOGlQQCVwxoAnVDItMJ1UiTh8Po",
        "https://mega.nz/embed/2X5BGbbL#ANEN9ACJGbZF9W9008nGbQDJh9QASoD1RWht1NNoMkA",
        "https://mega.nz/embed/CCxBhbzY#AHDHBACRLQ6MTkq7al6TYwCceYoAk8PojCrpvmrwYkY",
        "https://mega.nz/embed/qHQRESoS#AOe1zwCGablOT-sHxiZ9owC_twUALraJThRwQ8YeLqM",
        "https://mega.nz/embed/OaAzDSLD#ALXXfQDfKyBx8tZfzWO9mwB7FV4AgTEpcXOCHc2lgsg",
        "https://mega.nz/embed/PLgDSCSZ#ANvSvAB2C717nec7HRFAeQBmbYkA7_dMe9Ih9B2f8MM",
        "https://mega.nz/embed/vWByiCyK#AM01_AAeKMkMV9vNkJ_CeQCeTtwAas8tDMwta5BQXJ8",
        "https://mega.nz/embed/DTAE3L7b#AK6g9QDOfOL3OSKYcbkXBgAiZ60ARTUu9xWV83Gmf5A",
        "https://mega.nz/embed/uDgywZYB#ANscxQAMEloWecnZEUKlUwBBTWAA7413FqpZbhGzfoc",
        "https://mega.nz/embed/GD4CATbK#AGINiQATBX9-KQeF71tOTADxrsYAWEblfrUgPO-6uHM",
        "https://mega.nz/embed/qbxUDJIR#AByuywBOjW3kFbOKmpDwEgDZ4kIA3INR5MmKFJr0CEA",
        "https://mega.nz/embed/CD5HlDYS#ADnl5gDfsz6_foxnIO8ODAA9W8QAOeaZv3LnQyAALzE",
        "https://mega.nz/embed/7GwjDTgb#ADG_rABHzHJJD9_ZjO7TjABR7VUA6f6HSUT2y4wWYuY",
        "https://mega.nz/embed/LfBSjagB#AG2EIADUiHTTn539LltC5ACk5z8A02ul0yPkGi4txkY",
        "https://mega.nz/embed/jHQTASSZ#AF4b6QDk2gjmEypzKwHuCwDzpi4A6bDy5hmLoytm4dI",
        "https://mega.nz/embed/2Hw13ShB#AIaqswCqP-eG7WbW4X_U5QDuTtEAmdTuhoWmbeFWFa4",
        "https://mega.nz/embed/mfg3DaiD#APCLMgB1eslPn-mHK7FuTAByInkAT7dhT72RJistQ5c",
        "https://mega.nz/embed/mK5FHIKC#APi3FwABnUF6QciZgMaT8QB82CwA6vTfetE2tYCzJuc",
        "https://mega.nz/embed/eLwxVLJT#AB1IpACcJLsxb3HSV63MTAC-fRsAXLKvMSuPzleZ9IY",
        "https://mega.nz/embed/vG5EVAaK#AG39pABrXu3BlrkWfm4bjABmBVkAR5u_wd0J336xOT4",
        "https://mega.nz/embed/SL5jgaaZ#AGNfLQCOwhfk0e5Nn3vS3gBXwP8ASKjj5JHRJJ_q2Xg",
        "https://mega.nz/embed/KLpWBRZa#AOSD9wA5NSddJrhXEBIVKgBXsGkAPVxnXUiyURB1RG4",
        "https://mega.nz/embed/mGhSybgb#APAPNwBX75gpXFUuThp7_wD1g4QAQWvvKagNsU72MeM",
        "https://mega.nz/embed/qPhEgK4Y#AOW4xwBFmVNrPwKnEBd3-ACz49MAxvQka-oz7xDkGww",
        "https://mega.nz/embed/yHoGFSBA#AJ1ElgAJLMXt6QLTBxVOvwDJ2FQA4lFE7fyDKAe_Dng",
        "https://mega.nz/embed/aLw1XLbA#AKLWkgDzD790EVzePOeuQwB_F4IAgjCEdNJCBDwF3qs",
        "https://mega.nz/embed/bL5R1QjB#AFtM-QCmPJ29ysPkEaJa9wBqZ1UA_SrxvWMiPxGe1b8",
        "https://mega.nz/embed/XZ4EkChB#L90iEbAQUrvpANGMGCzvL-2Vv9OtfPlVK_1gcVK6UMM",
        "https://mega.nz/embed/mGgl0KAC#AJ4ungDlc8g6XkLT_MbCMgBUOHwARnD-OhHKvPxMd48",
        "https://mega.nz/embed/6X4hja6L#AABMqACuo2CmoS48nqElaQCOFJEAfEMXpjfcn57ckbE",
        "https://mega.nz/embed/nGggEAaa#AD30DwAnTpv-2G_i-otMMABNJ-oAWixY_gDCofrejjg",
        "https://mega.nz/embed/CHpTgaTB#AB08qABVdYWQiJjETQuZAgA6mo4A7glYkH5wVU0A34w",
        "https://mega.nz/embed/Xa4hDIqD#AI1JFgCBPOXtDhdE6H_0FwDsSFUA9QRV7Uo7JegGF9Q",
        "https://mega.nz/embed/6WQx0AJZ#AOGuNgCI-fSRcpEvmbMNOQAzOB8AgIGHkR3_jJlYbu0",
        "https://mega.nz/embed/qXx2jZYI#ADjmNwCgL935RIhpWMorVABzBXEA8En--eb5O1jSzng",
        "https://mega.nz/embed/Xb4REKgQ#APTCuwCuZF14JpmPWXSjuQACBsQAQ7rJeISWoVnczKw",
        "https://mega.nz/embed/WCxV0BLS#AHIyOgD_nNCoYyR3w8lKfwAl0rgASBWjqF0bc8MLxGs",
        "https://mega.nz/embed/yK413TiL#AAL7LQDmME2i7QDkt4stwgBOQbQAgYOrosGXpbeUAWM",
        "https://mega.nz/embed/mDImBSYJ#AMvKlAAn4RRB6lVdJUgH3QAKgy0AjlwgQf3HJCWs2yQ",
        "https://mega.nz/embed/jeIWRIza#AHMHNQChxdzRSL-Yr9HUegBEI38Awqlf0c2t06-Y9PU",
        "https://mega.nz/embed/7eYVjazS#AJkQcQAHzFeYT6KFqwB2EwCjsyIAcVykmDF3hasWdF4",
        "https://mega.nz/embed/fWBXjTCK#AFPfwwAtW0vfZcNPyBZx3gDbM6YAAETO3wv0q8iMYYQ",
        "https://mega.nz/embed/EdkW3bSA#tM1W37gO0ZstoBq6wzzsll52rGDIsGV_pYUXufWZIPc",
        "https://mega.nz/embed/2GYRAbjb#AFfk5QDTBPN9sqVj1lDmSQBHDPIAHiktfbf6AtbRXSs",
        "https://mega.nz/embed/XCZg1a7S#AOkCSAD1rOH0-_frBC4OKQCjLLEA-n-X9MQrlgQP73Y",
        "https://mega.nz/embed/qShlRKDT#AIG5TgCUIeX0tf1tYlHXUwAYqUMAXM3k9I3LWWJImVU",
        "https://mega.nz/embed/yP53QLib#ADesuwCKrhwy6Z6sVSxfEAAs5kEAwbIlMjQa9VV_0GE",
        "https://mega.nz/embed/2ToS1S5C#AMCLxAD7DOWWLxu5lP15dgA824MAvrr2ls86dJTZMfs",
        "https://mega.nz/embed/raIkTZ7D#ALeDagDhTEnmUGa4k_KelABwIjcAOKJs5qtHFZNGN5g",
        "https://mega.nz/embed/XX4UVZQL#AOi2-gBPjR3J4Wv3G8RTDgCcCfYAbUxCybUxUxv6dRI",
        "https://mega.nz/embed/TaIRQajQ#AM3KdwC4EignjRsLSuJ3awCWCzoAWR0NJyq02UqOXY8",
        "https://mega.nz/embed/ze5CVSJS#AB_PqQD2B2CEalmSHh899wAVpq8A7YgUhGsurR5DXnY",
        "https://mega.nz/embed/aCBBTDDb#AO2V3wAKTXhCgaqqCiRPwwBc-74AcnlfQiIh-goYhWQ",
        "https://mega.nz/embed/XDgGkZLK#AFJBGQCsrRBbvV9XJy6oPgBW8WYAwE9YW8onIyfq5j4",
        "https://mega.nz/embed/HXRQAJzB#AH6ltgAu6RWUklNIqLoYGgDGhIcA-3D1lLbwGajqAzk",
        "https://mega.nz/embed/ObYVyIbJ#AKBr-QBlrQTL5bul_IRssgDy3yAAFTHly11alfyVpNw",
        "https://mega.nz/embed/6Lp2TBaL#AGFGdQAxzEQBt8YFS8xpBACGj20Axf7vAaAUK0stv6E",
        "https://mega.nz/embed/WfwEmabK#ALjzugBEsZoxEg9z6H4VvQCOAt0A2gfgMZGlKuinxwQ",
        "https://mega.nz/embed/afIiUDAT#AHxaiAD6j7Y8P1Ta0hMojQCi28cA51RZPBe9r9IzhFU",
        "https://mega.nz/embed/DDIljSZa#AIpXsQBwHNIKJE9lJuuJgwCZQLEA5vg-CtTrSibqk2M",
        "https://mega.nz/embed/TLAGVZ4C#AJBlHgA7feL4huVbrXCVBQAnvaMAB9l3-LHc9q1FzxY",
        "https://mega.nz/embed/XLIiyKSD#AI2xeQASpd77mVSZ8pUcTACLcWUAmyHG-9DStfJKhtE",
        "https://mega.nz/embed/uaQXBJSL#AM5HGwAoHNn_LxXOWP_ZkgBxRtMAdTRw_zEOr1ig-Zk",
        "https://mega.nz/embed/PCAQyByZ#ABmb0gBp6jors3CRT_VczADhvfAAZMN4K-MX-U9ZX2o",
        "https://mega.nz/embed/GLxSlIqS#ABY_QgCeqG6fesah_yFbVwDONAsAqY0Xn4SVy__DqOI",
        "https://mega.nz/embed/SCZ0EAhL#AMUAbwDF6DAvLfF590CeLAAh8uIAAI7lL9b5lPdIJhA",
        "https://mega.nz/embed/baIABRLa#AOQURgCFh0Zi8dnDe35tJgBncHAAoZNHYlJFK3vMWP0",
        "https://mega.nz/embed/2WxlXBAa#ADwdTAAjnVcdydhtgHNPUQA0gJYAKpN5HaSfOICqjjQ",
        "https://mega.nz/embed/aPxyXa5D#AKmm6gDMwW-IO79oKFmM5gAfkVUAPGzOiCdoGSgE7JQ",
        "https://mega.nz/embed/vfwlTCbQ#APKe3ABz2Eil0i_hpdscGwBUcwkAuoQXpZNTAqWMo3s",
        "https://mega.nz/embed/DKAyjY5J#ANUolgDxMMtNdxfd7uxsnQD_xmIA6te-Tanbsu5HpQc"
    ],
    nombresEpisodios: [
        "Herr doctor Tenma",
        "Asesinato",
        "La noche de la ejecución",
        "La chica de Heidelberg",
        "Artículos de desapariciones",
        "La mansión de la tragedia",
        "Perseguido",
        "El mercenario y la niña",
        "Borrar el pasado",
        "Kinderheim 511",
        "Un experimento insignificante",
        "Petra y Schuhmann",
        "El último hombre, la última mujer",
        "Be my baby",
        "La confesión de Wolf",
        "Reunión",
        "Cinco cucharadas de azúcar",
        "El abismo del monstruo",
        "Viaje a Freinheim",
        "Unas felices vacaciones",
        "La trampa de Lunge",
        "La confesión de Eva",
        "Alrededor de una mesa",
        "El chico de los jueves",
        "El bosque secreto",
        "La prueba",
        "Un sólo asesino",
        "Ejecución",
        "La decisión",
        "A plena luz del día",
        "Santuario",
        "Escenas de una infancia",
        "El fin de la oscuridad",
        "Un héroe sin nombre",
        "El monstruo que siembra el caos",
        "El monstruo sin nombre",
        "El demonio ante mis ojos",
        "El infierno en sus ojos",
        "Grimmer",
        "El fantasma del 511",
        "Las aventuras de Steiner el magnífico",
        "El detective Suk",
        "Dobles tinieblas",
        "El rastro del monstruo",
        "Ángulo muerto",
        "Las puertas de la pesadilla",
        "Lo que te da más miedo",
        "La crueldad más extrema",
        "La mansión de las rosas",
        "La carta de amor del monstruo",
        "El abogado",
        "La decisión",
        "La huida",
        "La habitación 402",
        "El viaje sin fin",
        "Aquella noche",
        "Odio este trabajo",
        "El hombre que vió al diablo",
        "El hombre que sabía demasiado",
        "La puerta de los recuerdos",
        "Disfrutar la comida",
        "Asesinatos inconexos",
        "La angustia de bebé",
        "Las huellas de Johan",
        "¿Ya has vuelto?",
        "He llegado",
        "Ruhenheim",
        "Un hogar tranquilo",
        "El pueblo de la masacre",
        "La ira de Steiner el magnífico",
        "El hombre sin nombre",
        "El paisaje final",
        "El auténtico monstruo",
        "Degradación"],
    fechaEstreno: '2004',
    puntuacion: 9.2,
    categoria: ['Anime', 'Serie'],
    verticalbanner: require('../assets/images/Monster-verticalbanner.webp')
  }, 
  {
    id: 'Devil May Cry',
    nombre: 'Devil May Cry',
    descripcion: 'Dante está a cargo de una tienda que hace de todo llamada Devil May Cry. Con un mal carácter y una mala paga hace los trabajos para saldar todas sus deudas. Después de su primera misión ha tenido que quedarse con una niña que según él es insoportable, pero esa niña tiene algo especial, es la heredera de una familia millonaria y de un poder que ni ella conoce.',
    fondo: require('../assets/images/DMC_Banner.png'),
    logo: require('../assets/images/DevilMayCry.png'),
    capitulos: 12,
    fuente: [
  "https://mega.nz/embed/HnAxnAwa#DZWIZwhpcbL8pE4TzcKPUsf2cHRsCDH6_429Ev8-7gY",
  "https://mega.nz/embed/miYzjYZa#hpE3mn78CO2KRjQVHbajEIE9QRE6T4ZNJUkIvBdrUhY",
  "https://mega.nz/embed/vjYh1Kza#LRMiqLgNWHEt52EGC_CKLPak3ochfeNEkTl2g08J9lw",
  "https://mega.nz/embed/f6IhWKpR#e1FyZ5hdWGqoLPIy25PDQlHMMai0x-0BjeMap1sPRgc",
  "https://mega.nz/embed/WyRH1YAK#UIRYlmREkMj0Z5K3VXDd3fGU6TeCBVAZ7DU0nKe0SP4",
  "https://mega.nz/embed/6yBhWICZ#HgXpfhLrPIZ_mMmMlIclzNtkMEwATwJjBUJspmeqeiE",
  "https://mega.nz/embed/2iRzUShZ#kM51LkVribTmU8PxzZf6L2XJqH7PU5x4mhnHN9xcPdA",
  "https://mega.nz/embed/67IRAK6b#9kjybJD4vzb5CcDFSoQWQHFuMLUX9PXCEioZj-SLaYM",
  "https://mega.nz/embed/u7YFyCoB#jfZcSR3RRIySisgjA5tT5DTztcx4clGVGst9C_d26v0",
  "https://mega.nz/embed/HiYVmYJI#H8iaruZNkAXWfKlR56JqWKP1aWsOhz0wjHNnoNDEg_s",
  "https://mega.nz/embed/umZhwIaI#tb0ovvQJCt0tkbLVK1pQGcH-lxS28JJy47Nd2c1FuqM",
  "https://mega.nz/embed/v2QTnYqK#7_Sy-itUoYAiEYyJXjaG-VutnE67aIn49oDMG9GYIFU"
],
    nombresEpisodios: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13"
    ],
    fechaEstreno: '',
    puntuacion: 5.8,
    categoria: ['Anime', 'Serie'],
    verticalbanner: require('../assets/images/devil_may_cry_v.webp')
  },
  {
    id: 'Solo Leveling',
    nombre: 'Solo Leveling',
    descripcion: 'En un mundo de cazadores superdotados y monstruos, un débil cazador adquiere poderes a través de un misterioso programa, lo que le lleva a convertirse en uno de los cazadores más fuertes y a conquistar las mazmorras más poderosas.',
    fondo: require('../assets/images/solo-leveling-bg.webp'),
    logo: require('../assets/images/Solo_Leveling_logo.png'),
    capitulos: 25, // 12 de T1 + 13 de T2
    fuente: [
  // TEMPORADA 1
  "https://mega.nz/embed/Pd8TXCiB#UhkyxZuaVuztYgtQ9FpFlmOznX5kV6FsoSiuiS_QkUg",
  "https://mega.nz/embed/PIFUlTYB#h9UfEbgryAPiGkMbOMdStjmrWwfgzfUZOxyGmuMRpgU",
  "https://mega.nz/embed/PUtziALS#l52dBskeEDKy15it5kiBGk7Y_tWe6dT7UqCb_5oceRQ",
  "https://mega.nz/embed/iNtxQTZZ#awKOXAHeL4qU_syZgBzE7nSfVcX0v4XFt9Pm_AAkfuM",
  "https://mega.nz/embed/iY0UXZoQ#Fqc3ZoIqZj3tw5YFKD7nqgYvAxU9do0rVLfR6AOXoBQ",
  "https://mega.nz/embed/XR8jUArI#WVPBY9vTDT5j_xVgE17d8GaXUi9svVqvbANcHIA1tlY",
  "https://mega.nz/embed/XZ8REB7A#pipIvHlVBcE3fenaujo4lzunhGYvHotDeNLoXoxCD_Y",
  "https://mega.nz/embed/3Z8GmbxD#E9j7n7BrXblflOh80fKVn1AE53et26hnD-gMWuaYkYA",
  "https://mega.nz/embed/WddlxTaS#JIzzLJUzUgX3nm96My1he2FJMHIpIpBLuzHeau3ikp0",
  "https://mega.nz/embed/CRcglJQR#DVpagTlya8cnhl4lethnT0-zAqzMy9Ka_XO-CnqcoX8",
  "https://mega.nz/embed/PZUS0KpD#12kGrf85KbeoO1PVUUwaiRyAPWfjqMHc552U2ll9Zhw",
  "https://mega.nz/embed/3UsFHLCZ#t7FvsTQkJfT0yC1CMWiYNtPPS_u11Q8jd5IHcyZuiD8",
  // TEMPORADA 2
  "https://mega.nz/embed/sdRwFRRb#XR-VwhuTj_uhnz9i0Jhv4aEz-fszDHBUc3OOyNKpl50",
  "https://mega.nz/embed/pJIUCSiD#O_8Vm8FiJbFGHM8jSd2LqontK8lAfV0vjB0qNJ6pqSo",
  "https://mega.nz/embed/8IhG2JxD#g-Wf6B5ftzbP93zJHv8h5wKsv6ni1t-fnKLZnNDjlh8",
  "https://mega.nz/embed/wcYn1BqL#gUokZUr5gGYJH-NHM8Yk3xj-tn9MC2Vg0aya5H18C7A",
  "https://mega.nz/embed/1UwRCLYT#hre5E4O9mtN-TtRr5OUeeyge6Qm7shFULfT7EOqHhL0",
  "https://mega.nz/embed/MQ5TQDQY#GhL6wdfe_T3LMiO96L6N4vkYS4n9qk3X-GgBqDMb4i0",
  "https://mega.nz/embed/VNYCGI6Q#11Xz05Ff-FTDzYmFs5Reszq_q8-KwsRpUZZ3qG1qI2E",
  "https://mega.nz/embed/dVIjwDYK#UGrVt9iLe5X7zGFaaUCk7Apa8lSSEVzLYE5pxEx0iBM",
  "https://mega.nz/embed/AUhjlDJZ#29VtkXKdISpreOOPlqcgevT7jiCIejzTrBHaoXmv9KA",
  "https://mega.nz/embed/VRIhmYQA#Uo5EIB24-kuehfJeFySYgmTcPvC_O55kyE-BULrgf5o",
  "https://mega.nz/embed/VA5RTRKS#nHrfMV4lCQF2Mzb4_4HQUmwrbl0NQ_kt6R5FiJ5r4WA",
  "https://mega.nz/embed/AFR21CxR#LfNy_4SSyBr8GYBpUJzf_u6pRfolrc79g1m8xQE-tYQ",
  "https://mega.nz/embed/8ExRVTYD#hkE2rjlADCmksk5S_-18MHUUXTxJ3-AutWv5ySw3_EA"
],
  nombresEpisodios: [
  // TEMPORADA 1
  "T1 - 1. Ya estoy acostumbrado",
  "T1 - 2. Si tuviera otra oportunidad",
  "T1 - 3. Es como un juego",
  "T1 - 4. Tengo que hacerme más fuerte",
  "T1 - 5. Un muy buen trato",
  "T1 - 6. Comienza la verdadera cacería",
  "T1 - 7. Veamos hasta dónde puedo llegar",
  "T1 - 8. Qué frustrante",
  "T1 - 9. Has estado ocultando tus habilidades",
  "T1 - 10. ¿Qué es esto, un picnic?",
  "T1 - 11. Un caballero defendiendo un trono vacío",
  "T1 - 12. Surjan",
  // TEMPORADA 2
  "T2 - 1. No eres de Rango E",
  "T2 - 2. Parece que tú mismo no lo sabes",
  "T2 - 3. Aún queda mucho camino",
  "T2 - 4. Tengo que dejar de fingir",
  "T2 - 5. Estamos entrenados para esto",
  "T2 - 6. No menosprecies a los míos",
  "T2 - 7. El décimo Cazador de rango S",
  "T2 - 8. Mirar hacia arriba me estaba cansando",
  "T2 - 9. Valió la pena",
  "T2 - 10. Necesitamos un héroe",
  "T2 - 11. Se va a poner aún más intenso",
  "T2 - 12. ¿Eres el rey de los humanos",
  "T2 - 13. Al siguiente objetivo"
],
  fechaEstreno: '2024',
  puntuacion: 8.7,
  categoria: ['Anime', 'Serie', 'Ciencia ficción'],
  verticalbanner: require('../assets/images/solo-levling-vbanner.png')
},
  {
    id: 'Fear Street Part One: 1994',
    nombre: 'Fear Street Part One: 1994',
    descripcion: 'En 1994, un grupo de adolescentes descubre que los sucesos que aterrorizan su ciudad desde hace generaciones podrían estar conectados. Además, puede que ahora les toque a ellos protagonizar la pesadilla. Primera parte de la trilogía basada en las famosas novelas de miedo de R. L. Stine.',
    fondo: require('../assets/images/fearstreet1banner.webp'),
    logo: require('../assets/images/fear_street_part_one_1994-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/bo4SDYwa#shINqPXVxhQmrEm3OxzQC2WSZPvI3O88btk5igk18tA'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2021',
    puntuacion: 5.4,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/fear_street_part_one_1994-vertical-banner.jpg')
  },
  {
    id: 'Fear Street Part Two: 1978',
    nombre: 'Fear Street Part Two: 1978',
    descripcion: 'En 1978, Camp Nightwing está dividido en campistas que vinieron del pueblo oprimido de Shadyside y consejeros que vinieron del próspero pueblo de Sunnyvale. Cuando los horrores del pasado de ambos pueblos cogen fuerza, estos dos grupos deberán unirse para resolver un misterio terrorífico.',
    fondo: require('../assets/images/fear_street_part_two_1994-banner.jpg'),
    logo: require('../assets/images/fear_street_part_two_1994-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/T1QgxJQa#h6J5ag6A6mBgqsYzE4KDPj3AmlUP8PaPW0IrsfmtAzc'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2021',
    puntuacion: 6,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/fear_street_part_two_1978-vertical-banner.jpg')
  },
  {
    id: 'Fear Street: Prom Queen',
    nombre: 'Fear Street: Prom Queen',
    descripcion: 'Una noche de primavera... la suave luz de la luna... cinco hermosas candidatas a reina del baile... parejas bailando en el baile de graduación del instituto Shadyside... estos deberían ser los ingredientes del romance. Pero si se añade un brutal asesinato, y luego otro, y otro, la receta se convierte rápidamente en horror. Lizzie McVay se da cuenta de que alguien está asesinando una a una a las cinco candidatas a Reina del Baile... ¡y que ella puede ser la siguiente en la lista! ¿Podrá detener al asesino antes de que el baile termine para siempre?',
    fondo: require('../assets/images/fearstreetpromoqueenbanner.jpg'),
    logo: require('../assets/images/Fear_Street_-_Prom_Queen_(logo).png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/TBFnwYKJ#AtvPe-4RSVOVToG8uTvYns5luN06pcEeZO2L5XuJXZs'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2025',
    puntuacion: 3.5,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/fearstreetpromqueenvertical.jpeg')
  },
  {
    id: 'Dune',
    nombre: 'Dune',
    descripcion: 'En el Año 10191 el desértico planeta Arrakis, feudo de la familia Harkonnen desde hace generaciones, queda en manos de la Casa de los Atreides por orden del emperador. Con ello les cede la explotación de las reservas de especia, la materia prima más valiosa de la galaxia, necesaria para los viajes interestelares y también una droga capaz de amplificar la conciencia y extender la vida. El duque Leto (Oscar Isaac), la dama Jessica (Rebecca Ferguson) y el hijo de ambos, Paul Atreides (Timothée Chalamet), llegan a Arrakis con la esperanza de mantener el buen nombre de su casa y ser fieles al emperador, pero pronto se verán envueltos en una trama de traiciones y engaños que les llevará a cuestionar su confianza entre sus más allegados y a valorar a los lugareños, los Fremen, una estirpe de habitantes del desierto con una estrecha relación con la especia.',
    fondo: require('../assets/images/dune_wallpaper_pc_hd_2021_by_andrewvm_dep0l32-pre.jpg'),
    logo: require('../assets/images/Dune_2021_transparent_logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/iQVzjLCC#wDTyAJm4vF5wluz95u6pWbewWLRqa1egfgoE-w8xbeY'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2021',
    puntuacion: 8.2,
    categoria: ['Película', 'Ciencia ficción', 'Acción'],
    verticalbanner: require('../assets/images/duneverticalbanner.jpg')
  },
  {
    id: '28 Semanas Después',
    nombre: '28 Semanas Después',
    descripcion: '28 Semanas Después es la secuela de 28 Días Después, una película que se centra en un virus que convierte a las personas en caníbales. En esta secuela, el virus ha sido erradicado y los supervivientes están regresando a Londres. Sin embargo, el virus vuelve a aparecer y los supervivientes deben luchar por su supervivencia una vez más.',
    fondo: require('../assets/images/28semanasdespuesbanner.webp'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/aQliDbxR#jhZ-j41NJ4kKb7yU-xL43UazOtQ5hSxVZyVFKyJrGQ4'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2007',
    puntuacion: 8.2,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/28_weeks_later-892655817-mmed.jpg')
  },
  
  {
    id: 'Megamente 2',
    nombre: 'Megamente 2',
    descripcion: 'Megamente 2 es una película de animación que sigue las aventuras del villano reformado Megamente y su amigo Minion. Después de derrotar a su archienemigo Metro',
    fondo: require('../assets/images/c61b6126c4d1fcd5c6c627e8487d6514b50c68a5d4726c5c1a1a50d631f98dd5.jpg'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/b44SQTYI#tSYvlIMppDPYr3oLSsSn92f5yxYuFpYfj8n3icShSF4'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 2.5,
    categoria: ['Película'],
    verticalbanner: require('../assets/images/Megamente2verticalbanner.webp')
  },
  {
    id: 'Berserk',
    nombre: 'Berserk',
    descripcion: 'Basada en una exitosa saga que se ha visto reflejada ya en un manga, una serie y un videojuego, esta es la primera parte de Berserk en formato largometraje. Nuestro héroe es un guerrero de espada en mano. Imbatible, deberá lidiar con otro luchador, de pelo y armadura plateada.',
    fondo: require('../assets/images/Berserkbannerlaedaddorada.jpg'),
    logo: require('../assets/images/A_Berserk.webp'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/nsQCATTS#nKIMu1Wlq_AfPEri9yJoma-HYsIEzwgt5UW2qMtwMWY'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 6.9,
    categoria: ['Película', 'Anime'],
    verticalbanner: require('../assets/images/berserk1vericalbanner.jpg')
  },
  {
    id: 'Carol',
    nombre: 'Carol',
    descripcion: 'Nueva York, años 50. Therese Belivet (Rooney Mara), una joven dependienta de una tienda de Manhattan que sueña con una vida mejor, conoce un día a Carol Aird (Cate Blanchett), una mujer elegante y sofisticada que se encuentra atrapada en un matrimonio infeliz. Entre ellas surge una atracción inmediata, cada vez más intensa y profunda, que cambiará sus vidas para siempre.',
    fondo: require('../assets/images/carolbanner.webp'),
    logo: require('../assets/images/carollogo.webp'),
    capitulos: 1,
    fuente: [''],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 7,
    categoria: ['Película', 'LGTBIQ+'],
    verticalbanner: require('../assets/images/carolverticalbanner.jpg')
  },
  {
    id: 'Call me by your name',
    nombre: 'Call me by your name',
    descripcion: 'Elio Perlman (Timothée Chalamet), un joven de 17 años, pasa el cálido y soleado verano de 1983 en la casa de campo de sus padres en el norte de Italia. Se pasa el tiempo holgazaneando, escuchando música, leyendo libros y nadando hasta que un día el nuevo ayudante americano de su padre llega a la gran villa. Oliver (Armie Hammer) es encantador y, como Elio, tiene raíces judías; también es joven, seguro de sí mismo y atractivo. Al principio Elio se muestra algo frío y distante hacia el joven, pero pronto ambos empiezan a salir juntos de excursión y, conforme el verano avanza, la atracción mutua de la pareja se hace más intensa.',
    fondo: require('../assets/images/call_me_by_your_name.jpg'),
    logo: require('../assets/images/call_me_by_your_name-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/Dk5WBIaY#MvcEwx9imXYLnsuOAZLIEYyHFRaLVx0FTIhbzf1R7Vg'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 7,
    categoria: ['Película', 'LGTBIQ+'],
    verticalbanner: require('../assets/images/call_me_by_your_name-vertical.jpg')
  },
  {
    id: 'Old Boy',
    nombre: 'Old Boy',
    descripcion: 'Oh Dae-su es un hombre de negocios coreano que un día es secuestrado y confinado durante años en una celda en la que sólo hay una televisión. Y, sin embargo, ignora por qué razón está allí... Segunda parte de la "trilogía de la venganza" de Park Chan-wook.',
    fondo: require('../assets/images/oldboybanner.jpg'),
    logo: require('../assets/images/oldboylogo.webp'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/z5wACY6R#U2zxqeyEqV0DRLMJbvjWnN0PPzZ0rT1iK1KOj2bWyMs'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 8.8,
    categoria: ['Película', 'Acción'],
    verticalbanner: require('../assets/images/oldboybannervertical.jpg')
  },
  {
    id: 'Secreto en la montaña',
    nombre: 'Secreto en la montaña',
    descripcion: 'En 1963, dos vaqueros, Ennis del Mar (Heath Ledger) y Jack Twist (Jake Gyllenhaal), se conocen mientras trabajan como pastores de ovejas en el remoto rancho de Brokeback Mountain. A pesar de sus diferencias, los dos hombres desarrollan una profunda conexión emocional y sexual que desafía las normas sociales de la época. A lo largo de los años, su relación se convierte en un secreto compartido, ya que ambos luchan por equilibrar sus sentimientos con las expectativas de la sociedad y sus propias vidas personales.',
    fondo: require('../assets/images/13140BROKEBACK-MOUNTAIN_banner_1.jpg'),
    logo: require('../assets/images/brokeback-mountain-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/0VZ1VBxI#UAOEV27DvQL5_JGzECsr7NyrFx1fLAeFGHtwf-LbFIY'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 8.8,
    categoria: ['Película', 'LGTBIQ+'],
    verticalbanner: require('../assets/images/secreto-en-la-montana-cover.jpg')
  },
  {
    id: 'Bocchi the Rock!',
    nombre: 'Bocchi the Rock!',
    descripcion: 'Hitori Gotou es una chica solitaria que sueña con ser parte de una banda de música. Sin embargo, su timidez y falta de habilidades sociales la han mantenido alejada de la escena musical. Un día, conoce a Nijika Ijichi, quien le ofrece unirse a su banda llamada "Kessoku Band". A pesar de sus inseguridades, Hitori acepta y comienza su viaje para superar sus miedos y convertirse en una talentosa guitarrista.',
    fondo: require('../assets/images/bocchi_the_Rock_Banner.jpg'),
    logo: require('../assets/images/Bocchi_the_Rock_Logo.webp'),
    capitulos: 12,
    fuente: [
      "https://mega.nz/embed/HpIShJLC#ctI8HW0liy6LKisBBc5t79fOCExQUAOZJJMUf9DI4FA",
      "https://mega.nz/embed/24JXSTYS#dFcI6ix46hZy7Aev5mhXO6UdZUKfXE9tZOUyhAV6kpg",
      "https://mega.nz/embed/LpwylAwK#PVq6zMxjfZdxt-oDan3r30pHOTD13vHcdGqcUWc1AsU",
      "https://mega.nz/embed/ypgzlahI#jZ4c2CZuhr_M9NbeOp0CxgSpeE2prqkjU1xYlclcRok",
      "https://mega.nz/embed/3xwkmJza#TFNYkIu8hEQf1JD1NUE8G7sJXAs-M1wvO4SBmTuQqko",
      "https://mega.nz/embed/7xRwzbzb#uSyc9hMgmLFFI2RtkEyE2fQlPtZ36h1wFqBjvHyqoOk",
      "https://mega.nz/embed/zghTQL6L#4CIOEd8gf7Uv-fT_QIl3ZzKjZh7p1HCftWzwvrmZhoI",
      "https://mega.nz/embed/b5gCwY5D#m0d0hy0hVtahOR7437MROWvuvL1h-lym0obhPx3aZFA",
      "https://mega.nz/embed/WtpGwarB#RaFbLnDoyPE6lW4M4IbkkgsMUTCdiqI-jeEt_DYsy_g",
      "https://mega.nz/embed/TwQh2YSJ#vWhUfKaVaG3kK9Q3ciGHIw3gzb4OLpUi7Dl1Uq9vwl4",
      "https://mega.nz/embed/PlpT2RQD#YSapNwN6-6DKDsOD2fziue2lthoxq5-QApO3pWgAZjU",
      "https://mega.nz/embed/m1QQSBjL#D83s6K099uE7zFdP8LSi7r_aQbs3qVed6x5IyJtI1os"
    ],
    nombresEpisodios: [
      "01 - La caída de Bocchi",
      "02 - Hasta mañana",
      "03 - Llegada rápida",
      "04 - Jumping Girl(s)",
      "05 - Un pez que no vuela",
      "06 - Ocho vistas insuperables",
      "07 - Hasta tu casa",
      "08 - Bocchi The Rock",
      "09 - Las escaleras de Enoshima",
      "10 - After Dark",
      "11 - Un atardecer duodecimal",
      "12 - Cae la mañana"
    ],
    fechaEstreno: '2024',
    puntuacion: 8.8,
    categoria: ['Serie', 'Anime'],
    verticalbanner: require('../assets/images/bocchi_the_rock_re-639827727-large.jpg'),
    // Temporalmente comentado - archivos de música removidos
    /* soundtracks: [
      { title: "Seisyun Complex", file: require('../assets/Music/Bocchi the rock/01. seisyun complex.mp3'), duration: "3:24" },
      { title: "Distortion!!", file: require('../assets/Music/Bocchi the rock/03. Distortion!!.mp3'), duration: "3:12" },
      { title: "Guitar, Loneliness and Blue Planet", file: require('../assets/Music/Bocchi the rock/05. Guitar, Loneliness and Blue Planet.mp3'), duration: "4:15" },
      { title: "That Band", file: require('../assets/Music/Bocchi the rock/07. That band.mp3'), duration: "3:48" },
      { title: "Never Forget", file: require('../assets/Music/Bocchi the rock/11. Never forget.mp3'), duration: "4:02" }
    ] */
  },
  {
    id: 'Aqui no hay quien viva',
    nombre: 'Aqui no hay quien viva',
    descripcion: 'Aquí no hay quien viva es una serie de televisión española que se emitió desde 2003 hasta 2006. La trama gira en torno a los vecinos de un edificio en Madrid, sus relaciones, conflictos y situaciones cómicas. La serie es conocida por su humor y personajes entrañables.',
    fondo: require('../assets/images/Anhqv.jpg'),
    logo: require('../assets/images/AnhqvTitle.png'),
    capitulos: 17,
    fuente: [
      "https://mega.nz/embed/0AZ2SQhY#cV3LdY4ieRMMoxPzE3VGNm9fwF_EpiZ2wCVkCml0MaM",
      "https://mega.nz/embed/kUBEyYQa#NB6DG9sqt8h1rpsmayC-7eStLhsLFMLiNvbcUlegQM8",
      "https://mega.nz/embed/IAZxXTKY#gbXbkiR8D9mwWDRc8nAxC5WzS4qborZA3EilyG_-vOo",
      "https://mega.nz/embed/sQxwRBID#7LACVFBbCl-ZeGtxnpbfcETOmudgOlVq60PnANfRLQ8",
      "https://mega.nz/embed/QEwgjYqb#EpkQztS_0llyRTpaPl2ffH-oCyfgXzb8IFsrWz4zCr8",
      "https://mega.nz/embed/RRgGjRrC#t1_e7nF9AUNOFxTFTXWrdXpy7U6MELTPxGmTM8VVjUU",
      "https://mega.nz/embed/MYQByC6Y#mFvNXGK_zsJcoy3jl3PjvxfqkiQzkqbg7cdsUC7m5b8",
      "https://mega.nz/embed/RYoWzYhB#h4tTzyHCvtfIG_fsd0WT6H1jWFMkT6IfHDktKNUOahk",
      "https://mega.nz/embed/INJClarT#_UnGT_idAH7Fzg5RonAKDOUHxLoPvzomOq8Un7dCwKA",
      "https://mega.nz/embed/8NIGjB5Y#BXMBqIO7nUQRI0C-0PozmxOqDSG7TPzOY3zfvwkZnbQ",
      "https://mega.nz/embed/JIYlCK5Y#8tL3njWULrc68xsz0sINOJXZ6cQD8DBm50rowkolnD0",
      "https://mega.nz/embed/IYgEhRQa#7TI3L2CpHtOhz-1xfnEfhadcAZOnEglyxtCww-Q_PKY",
      "https://mega.nz/embed/NZwGzBxI#Z33OmXMiUZTVU6M1jq6MhceG1DLQ4X2cLyXsgkhOT_s",
      "https://mega.nz/embed/xAgGhJiB#nRgaLL7stygWa_sdl-kGZIO6qQAck8VWxxeunkTh5OM",
      "https://mega.nz/embed/gZ5H0JJZ#fGUv9zXmAcb7XygutUjnhm5PdyUvsae28aW05pD59HU",
      "https://mega.nz/embed/ZZwhWIpB#jXkpLe6phjLkIZg-xJcfi8s4Cs9iWuwZd1Q-G_Dm8SM",
      "https://mega.nz/embed/EBhwEboD#tcCEL9HZiwO-K6u0gEqdgBcZE-RlwplXdFHhX1iREB0"
  ],
    nombresEpisodios: [
    "01 - Érase una mudanza",
    "02 - Érase una reforma",
    "03 - Érase el reciclaje",
    "04 - Érase un rumor",
    "05 - Érase un niño",
    "06 - Érase un resbalón",
    "07 - Érase una rata",
    "08 - Érase un indigente",
    "09 - Érase una de miedo",
    "10 - Érase un dilema",
    "11 - Érase un traspaso",
    "12 - Érase un sustituto",
    "13 - Érase una fiesta",
    "14 - Érase una avería",
    "15 - Érase un anillo",
    "16 - Érase una Nochebuena",
    "17 - Érase un fin de año"
  ],
    fechaEstreno: '2003',
    puntuacion: 10,
    categoria: ['Serie', 'LGTBIQ+', 'Comedia'],
    verticalbanner: require('../assets/images/aqui_no_hay_quien_viva-150319925-mmed.jpg')
  },
  {
    id: 'Star Wars. Episodio I: La amenaza fantasma',
    nombre: 'Star Wars. Episodio I: La amenaza fantasma',
    descripcion: 'Primer capítulo de la trilogía de precuelas de Star Wars, en el que se nos presenta a Anakin Skywalker, un niño esclavo con un gran potencial en la Fuerza. En el Episodio I aparece el villano Darth Maul, un temible Sith con un sable de luz de doble hoja. Los Sith son los amos del lado oscuro de la Fuerza y los enemigos de los Jedi. Fueron prácticamente exterminados por los Jedi hace mil años, pero esta orden del mal sobrevivió en la clandestinidad.',
    fondo: require('../assets/images/starwars1b.webp'),
    logo: require('../assets/images/Star-Wars-transparent-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/4BIxxDiT#YyYKlHAeJViWBB4LSRo7csHpSIpp9qC2UfVi4x6xecE'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2005',
    puntuacion: 8.2,
    categoria: ['Película', 'Ciencia ficción', 'Acción', 'Star Wars'],
    verticalbanner: require('../assets/images/starwars1v.jpg')
  },
  {
    id: 'Star Wars. Episodio II: El ataque de los clones',
    nombre: 'Star Wars. Episodio II: El ataque de los clones',
    descripcion: 'Segundo capítulo de la trilogía de precuelas de Star Wars, en el que Anakin Skywalker se convierte en un Jedi y comienza a enamorarse de Padmé Amidala. En el Episodio II aparece el Conde Dooku, un antiguo Jedi que se ha pasado al lado oscuro y lidera el ejército separatista Droid. Los Sith son los amos del lado oscuro de la Fuerza y los enemigos de los Jedi. Fueron prácticamente exterminados por los Jedi hace mil años, pero esta orden del mal sobrevivió en la clandestinidad.',
    fondo: require('../assets/images/starwars2banner.webp'),
    logo: require('../assets/images/Star-Wars-transparent-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/VMohUZYa#EUpHouwnbVumaMVXi7etvC_PEvpQSGK1ml-_fi0Imhg'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '1999',
    puntuacion: 8.2,
    categoria: ['Película', 'Ciencia ficción', 'Acción', 'Star Wars'],
    verticalbanner: require('../assets/images/star_wars_episode_ii_attack_of_the_clones-495166632-large.jpg')
  },
  {
    id: 'Star Wars. Episodio III: La venganza de los Sith',
    nombre: 'Star Wars. Episodio III: La venganza de los Sith',
    descripcion: 'Último capítulo de la trilogía de precuelas de Star Wars, en el que Anakin Skywalker definitivamente se pasa al lado oscuro. En el Episodio III aparece el General Grievous, un ser implacable mitad-alien mitad-robot, el líder del ejército separatista Droid. Los Sith son los amos del lado oscuro de la Fuerza y los enemigos de los Jedi. Fueron prácticamente exterminados por los Jedi hace mil años, pero esta orden del mal sobrevivió en la clandestinidad.',
    fondo: require('../assets/images/starwars3banner.webp'),
    logo: require('../assets/images/starwars3logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/jBcRhBSK#yFiZj-DF0e5RYCASBjGCSbplESYIweEFth9Trwl5Rmk'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2005',
    puntuacion: 8.2,
    categoria: ['Película', 'Ciencia ficción', 'Acción', 'Star Wars'],
    verticalbanner: require('../assets/images/starwars3verticalbanner.jpg')
  },
  {
    id: 'Star Wars. Episodio IV: Una nueva esperanza',
    nombre: 'star Wars. Episodio IV: Una nueva esperanza',
    descripcion: 'Hace mucho tiempo en una galaxia muy, muy lejana ... Son tiempos de guerra civil. Naves rebeldes han atacado desde una base secreta y han obtenido su primera victoria contra el malvado Imperio Galáctico. Durante la batalla, espías rebeldes lograron robar los planos secretos del arma más extrema del Imperio, la Estrella de la Muerte, una estación espacial blindada con suficiente potencia para destruir un planeta entero. Perseguida por los siniestros agentes del Imperio, la Princesa Leia se dirige velozmente a casa en su nave espacial, mientras resguarda los planos que pueden salvar a su pueblo y restaurar la libertad en la galaxia',
    fondo: require('../assets/images/Star-wars-4b.webp'),
    logo: require('../assets/images/Star-Wars-transparent-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/oYxhWKRS#pLgye3Ld05RfkcJbIOnc_-HUD89flVzKp-ci7uzZ3IM'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '1977',
    puntuacion: 9.8,
    categoria: ['Película', 'Acción', 'Ciencia ficción', 'Star Wars'],
    verticalbanner: require('../assets/images/starwars4v.jpg')
  },
  {
    id: 'Star Wars. Episodio V: El Imperio Contraataca',
    nombre: 'Star Wars. Episodio V: El Imperio Contraataca',
    descripcion: 'Hace mucho tiempo en una galaxia muy, muy lejana ... Son tiempos de guerra civil. Naves rebeldes han atacado desde una base secreta y han obtenido su primera victoria contra el malvado Imperio Galáctico. Durante la batalla, espías rebeldes lograron robar los planos secretos del arma más extrema del Imperio, la Estrella de la Muerte, una estación espacial blindada con suficiente potencia para destruir un planeta entero. Perseguida por los siniestros agentes del Imperio, la Princesa Leia se dirige velozmente a casa en su nave espacial, mientras resguarda los planos que pueden salvar a su pueblo y restaurar la libertad en la galaxia',
    fondo: require('../assets/images/Star-wars-4b.webp'),
    logo: require('../assets/images/Star-Wars-transparent-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/JUJG1BRL#ziSUyUIBD-8A0_rW1lhVZUkYM97mWguMEOINQEp6QxM'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '1980',
    puntuacion: 9.8,
    categoria: ['Película', 'Acción', 'Ciencia ficción', 'Star Wars'],
    verticalbanner: require('../assets/images/EpVv.webp')
  },
  {
    id: 'Star Wars. Episodio VI: El retorno del Jedi',
    nombre: 'Star Wars. Episodio VI: El retorno del Jedi',
    descripcion: 'Para ir a Tatooine y liberar a Han Solo, Luke Skywalker y la princesa Leia deben infiltrarse en la peligrosa guarida de Jabba the Hutt, el gángster más temido de la galaxia. Una vez reunidos, el equipo recluta a tribus de Ewoks para combatir a las fuerzas imperiales en los bosques de la luna de Endor. Mientras tanto, el Emperador y Darth Vader conspiran para atraer a Luke al lado oscuro, pero el joven está decidido a reavivar el espíritu del Jedi en su padre. La guerra civil galáctica termina con un último enfrentamiento entre las fuerzas rebeldes unificadas y una segunda Estrella de la Muerte, indefensa e incompleta, en una batalla que decidirá el destino de la galaxia.',
    fondo: require('../assets/images/sw6baner.jpeg'),
    logo: require('../assets/images/Star-Wars-transparent-logo.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/HJ8SkSKA#BIL07uN9VaVkUINSPH2uprZiZKutWHwaVMCU5RIuXBs'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '1983',
    puntuacion: 7.8,
    categoria: ['Película', 'Acción', 'Ciencia ficción', 'Star Wars'],
    verticalbanner: require('../assets/images/ReturnOfTheJediPoster1983.webp')
  },
  {
    id: 'Predator: Asesino de asesinos',
    nombre: 'Predator: Asesino de asesinos',
    descripcion: 'Tres de los guerreros más feroces de la historia de la humanidad se convierten en presa del asesino supremo de asesinos.',
    fondo: require('../assets/images/Predator-Killer-of-Killers-01.webp'),
    logo: require('../assets/images/pp_20cs_predator_killerofkillers_logo_v3_064729ee.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/LZcDTRoL#WfWCZamyDjYniWPSQWCTycCxT3GzAm3SJr4MDnGTuOg'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2025',
    puntuacion: 7,
    categoria: ['Película', 'Acción', 'Ciencia ficción'],
    verticalbanner: require('../assets/images/predator-killer-of-killers-poster-y-trailer-original.jpeg')
  },
  {
    id: 'La La Land',
    nombre: 'La La Land',
    descripcion: 'Mia (Emma Stone), una joven aspirante a actriz que trabaja como camarera mientras acude a castings, y Sebastian (Ryan Gosling), un pianista de jazz que se gana la vida tocando en sórdidos tugurios, se enamoran, pero su gran ambición por llegar a la cima en sus carreras artísticas amenaza con separarlos.',
    fondo: require('../assets/images/lalalandfondo.jpg'),
    logo: require('../assets/images/64389699-53f4-40cc-aae3-a8dddfc0b6b0.webp'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/fAUBnRZK#sur7jWgmIh5MdmT6X1emBZoCdyD7MNT4ZT3yTx38i68'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2018',
    puntuacion: 9,
    categoria: ['Película'],
    verticalbanner: require('../assets/images/La_ciudad_de_las_estrellas_La_La_Land-262021831-large.jpg'),
    // Temporalmente comentado - archivos de música removidos
    /* soundtracks: [
      { title: "Another Day Of Sun", file: require("../assets/Music/La La Land/Another Day Of Sun [WxCz0UNUNeQ].mp3"), duration: "3:47" },
      { title: "Someone In The Crowd", file: require("../assets/Music/La La Land/Someone In The Crowd [-62YbRZqxjs].mp3"), duration: "4:18" },
      { title: "A Lovely Night", file: require("../assets/Music/La La Land/A Lovely Night [trrH4sVZ0dQ].mp3"), duration: "3:56" },
      { title: "Mia & Sebastian's Theme", file: require("../assets/Music/La La Land/Mia and Sebastian Theme.mp3"), duration: "1:37" }
    ], */
  },
  {
    id: 'Jojos Bizarre Adventure',
    nombre: 'Jojos Bizarre Adventure',
    descripcion: 'La bizarra aventura de Joaquin Joestrella, un joven con una extraña habilidad para detener el tiempo y que se embarca en una serie de aventuras épicas junto a sus amigos y enemigos. Con un estilo único y personajes memorables, Jojo es una serie que combina acción, comedia y drama de una manera inigualable.',
    fondo: require('../assets/images/jojobaner2.jpg'),
    logo: require('../assets/images/jojologo.webp'),
    capitulos: 26,
fuente: [
      "https://mega.nz/embed/rVNVmJBZ#nLjfYTU5VWSXgeuMVSqS8_oq0qgm-Fp6NQLfg5TgJoA",
      "https://mega.nz/embed/zYNFVaKB#MYpdqVxMvi2odu-4b9WLzsSzpZha-WWxqCDwKgrjpDU",
      "https://mega.nz/embed/KIMDRCoZ#XJAALUnlgXf2Ffit0zH_cr2eGmEf_4niQctkiVc1kYA",
      "https://mega.nz/embed/zQUhXBjY#l2xX2oH6meg4rZt1AZ1KYfHaheOrxyYpEXp-GZ0f_X0",
      "https://mega.nz/embed/HM1khbTQ#_YDXOBXaVaeRUxWN2ZOYCAwmqNccvfMos2mdkBuUT2A",
      "https://mega.nz/embed/7QE3DLDZ#A6liwTDyi5mJF93ygjqxSILSi1_I5MVV4Ij9PLAs9iQ",
      "https://mega.nz/embed/WZUx3A7S#jNRsgt9zIpPnbhDuv8mL6mCYBNFdBA55rWdUYYDFZk0",
      "https://mega.nz/embed/PB9ADTAZ#grk-16q7JK69xbUA9yVksnrF7u4MJ7v8RR51zV9-_5Y",
      "https://mega.nz/embed/CQ8HmQ7D#JNXXHLM0jvp6lbvyaEN3BozZ_SjV_qRa83qUTzGVom8",
      "https://mega.nz/embed/nB03Wbbb#H5t9SObz5q8V36a7927z6Cscyp73nzAhr9O00D7eIy8",
      "https://mega.nz/embed/nUc1UZoC#nFCMXU_dqgGy4FC-kfR_nQ53DZBRvCbPRRCpEyBGCb0",
      "https://mega.nz/embed/qFkA2LRa#gJGLWG92upsE9yJF4UIwMJGWEUA5rnRMyjN3tcoj1TA",
      "https://mega.nz/embed/DQEjgJLQ#pkDoZ5IUTncd4FWGE6seoRb_hPSjlXFqxIptgcSH6hQ",
      "https://mega.nz/embed/6dNgRR6A#3aNlLIXEllPZOh1nmp0d0YEqxlerTTD0NttBPoquutA",
      "https://mega.nz/embed/qRtyTKQI#eGta171IbnMD0Jqwr7OVT6t9tYAuKyn1Sm2-QEw9ts8",
      "https://mega.nz/embed/3BUERLLT#pfYvbboABHJ62ny22M6I5ojHXloKoP4qc8hjgrS30wM",
      "https://mega.nz/embed/fUUjBAgY#dM1T4tkLO1ezbEFoW4qyoccnt8FGPTKTem1WnG-Y8I0",
      "https://mega.nz/embed/PIsQVZpK#-fzBas_0sy5BSaQ_X6M2dGYbDbb9i9tO1J1mY6f5rfo"
    ],

    nombresEpisodios: [
  "Episodio 1",
  "Episodio 2",
  "Episodio 3",
  "Episodio 4",
  "Episodio 5",
  "Episodio 6",
  "Episodio 7",
  "Episodio 8",
  "Episodio 9",
  "Episodio 10",
  "Episodio 11",
  "Episodio 12",
  "Episodio 13",
  "Episodio 14",
  "Episodio 15",
  "Episodio 16",
  "Episodio 17",
  "Episodio 18",
  "Episodio 19",
  "Episodio 20",
  "Episodio 21",
  "Episodio 22",
  "Episodio 23",
  "Episodio 24",
  "Episodio 25",
  "Episodio 26"
],
    fechaEstreno: '2012',
    puntuacion: 10,
    categoria: ['Serie', 'Anime'],
    verticalbanner: require('../assets/images/jojovbanner.jpeg')
  },
  {
    id: 'Dexter',
    nombre: 'Dexter',
    descripcion: 'Dexter es un forense de la policía de Miami que lleva una doble vida como asesino en serie. Utiliza su conocimiento del crimen para cazar a otros criminales que han escapado a la justicia, mientras lucha con su propia naturaleza oscura y los dilemas morales que enfrenta.',
    fondo: require('../assets/images/dexterbanner.webp'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 12,
fuente: [
      "https://mega.nz/embed/WN8zDTiR#WCxgP_ZSh3SkHHx-t8TdlCLhxeWU-dMIbYl9eH8N4_0",
      "https://mega.nz/embed/jRV1SLKa#rZiBhsItbltmjNlSKx8_v7SYep-vQDSd25eOxEhro0E",
      "https://mega.nz/embed/jYUGEYwQ#q9orBID7k5UzRnx91OU2hRJxN5hVME5Fxsv3lXt3JZg",
      "https://mega.nz/embed/LZsnXDTA#7Z8f_PtUdqXCG-u1sGBbbbxeKN9jW6_Dk7cJfJ_2cJk",
      "https://mega.nz/embed/GZNFHYoQ#l58QdCJHTkGUpXjrVOCZhdQcjrmgWP_vOhcddgTUzPE",
      "https://mega.nz/embed/vM1QzQhI#LNh1-pDMnPAZHQhiJ8NGm-lXo6G7BXQ61nU_zG7ujJQ",
      "https://mega.nz/embed/6RlhRDJb#8Fdvh9L-VRg0QRr-Kvk3sCPXntKtlbA5Nk1-JykiZd0",
      "https://mega.nz/embed/OIsGEKZQ#q7B9IK49uKk8oW_VacJ5XhdJab7r3N0ysKxAlun23nk",
      "https://mega.nz/embed/6EVilbYQ#YB72YNZTDnM_zRBBZ21MP-Gs4syd0osBvbj-Yz3xx8g",
      "https://mega.nz/embed/vQFyibpa#SR4yls0BiYqKEJDnb3_ZwPEbOCa8GQN4FEZ7lZwGFfk",
      "https://mega.nz/embed/3JMQESrD#r7XCgFzvKVDBKiYHQcIYUwMg3gIRnI_bCashiR_mhR4",
      "https://mega.nz/embed/HRlngaSB#PgPWj4PtHpS_3onz2F5cA8d8bJjrvREH4Z3Tij_KevI"
    ],

    nombresEpisodios: [
  "Episodio 1",
  "Episodio 2",
  "Episodio 3",
  "Episodio 4",
  "Episodio 5",
  "Episodio 6",
  "Episodio 7",
  "Episodio 8",
  "Episodio 9",
  "Episodio 10",
  "Episodio 11",
  "Episodio 12"
],
    fechaEstreno: '2006',
    puntuacion: 7,
    categoria: ['Serie'],
    verticalbanner: require('../assets/images/dexter-plastic-wrap-carroll-koester.jpg')
  },
  {
    id: 'Another Round',
    nombre: 'Another Round',
    descripcion: 'Cuatro profesores de instituto se embarcan en un experimento sociológico en el que cada uno de ellos deberá mantener la tasa de alcohol en su cuerpo al mismo nivel, durante su vida diaria, intentando demostrar de esa manera que pueden mejorar en todos los aspectos de su vida.  ',
    fondo: require('../assets/images/maxresdefault_m1608140893.jpg'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/qccCGLDK#48v-W4B2YuywEkx1FXR4FVnZMsF95ujw9TNt1CFLDZ8'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2020',
    puntuacion: 9,
    categoria: ['Película'],
    verticalbanner: require('../assets/images/anotherround.webp')
  },
  {
    id: 'Metal Gear: La Peli: La Comedia',
    nombre: 'Metal Gear: La Peli: La Comedia',
    descripcion: 'La película de Metal Gear Solid que llegó antes que Hollywood. Una gran, gran tontería. No hace falta haber jugado al Metal Gear para enterarse, este vídeo está hecho para que todo el mundo se pueda enterar.',
    fondo: require('../assets/images/metal_gear_solid_1_wallpaper_remastered_by_quixware_denggt6-pre.png'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/LJ1nhCYa#ZljhcX67SpJmmwjJD-cpa8mQoNTRdF5QslHobHbb4dg'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2020',
    puntuacion: 9,
    categoria: ['Película', 'Comedia'],
    verticalbanner: require('../assets/images/Metal Gear Solid poster.webp')
  },
  {
    id: 'Superman',
    nombre: 'Superman',
    descripcion: 'En un mundo cínico que ha perdido la fe en la bondad, Superman lucha por reconciliar su herencia kryptoniana con su crianza humana en Smallville como Clark Kent. Mientras protege a la humanidad, encarna la verdad, la justicia y el estilo americano, desafiando una era que considera estos valores obsoletos. Reinicio del universo DC en cine bajo la supervisión y dirección de James Gunn.',
    fondo: require('../assets/images/Imagen-de-WhatsApp-2024-12-16-a-las-11.34.11_7c201758.jpg'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/OQN2RBYJ#9m0cf-f8YYHbSwmbUF_enY8YZ5wMHzcfhZS2fSxKnNQ'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2025',
    puntuacion: 8,
    categoria: ['Película'],
    verticalbanner: require('../assets/images/Superman-2025-Movie-Poster_0fa402fb-520d-4f74-801a-6cef6014f01a.a8d25f15ef5b346137fe7f066292f8c3.webp')
  },
  {
    id: 'The VelociPastor',
    nombre: 'The VelociPastor',
    descripcion: 'Tras perder a sus padres, un sacerdote viaja a China, donde hereda una misteriosa habilidad que le permite convertirse en dinosaurio.',
    fondo: require('../assets/images/snBoFGZU4Kh7e9tzHktIwGsnze8.webp'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/nRkx3CBa#Xc6FKi4b8AzCINiyjDVLw58-XHKg9nqSU532GaFry3I'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2018',
    puntuacion: 3.5,
    categoria: ['Película', 'Comedia', 'Terror'],
    verticalbanner: require('../assets/images/R.jpeg')
  },
  {
    id: '28 años después',
    nombre: '28 años después',
    descripcion: 'Años transcurridos tras los sucesos de "28 semanas después", el virus de la ira ha regresado y un grupo de supervivientes debe sobrevivir en un mundo asolado por hordas de infectados. Realizada con un iPhone 15 Pro Max y con la ayuda de numerosos accesorios especializados',
    fondo: require('../assets/images/principal_28-anos-despues-cuando-se-estrena-donde-ver-en-espanol-latino.webp'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/GUMBERaJ#da7i0ItZfK__da6FdVSe9Em3easl2DHd-kZr7wlmnU4'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2018',
    puntuacion: 3.5,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/28_years_later-958240308-large.jpg')
  },
  {
    id: 'Nosferatu',
    nombre: 'Nosferatu',
    descripcion: 'Historia gótica de obsesión entre una joven hechizada y el aterrador vampiro encaprichado de ella, que causa un indescriptible terror a su paso.',
    fondo: require('../assets/images/wp14949418.webp'),
    logo: require('../assets/images/nobackground.png'),
    capitulos: 1,
    fuente: ['https://mega.nz/embed/gZ1XBI5L#yjyx4Wt-f0WWKKPHMmjls9lgzJqbLycWeS_RLm_UXZs'],
    nombresEpisodios: ['Película completa'],
    fechaEstreno: '2024',
    puntuacion: 7,
    categoria: ['Película', 'Terror'],
    verticalbanner: require('../assets/images/3kkr1vc9a2.jpg')
  },
  {
    id: 'Coldwater',
    nombre: 'Coldwater',
    descripcion: 'John traslada a su familia a un pueblo rural, se hace amigo de Tommy, que esconde oscuros secretos. La fascinación de John por Tommy crece a medida que su esposa Fiona comienza a sospechar. Se descubren verdades ocultas e ira reprimida.',
    fondo: require('../assets/images/MV5BM2RmZGU1ZGYtNjU2OC00NTQ0LTg2ZmItZDY2NmRiNDhiOWU5XkEyXkFqcGc@._V1_FMjpg_UX937_.jpg'),
    logo: require('../assets/images/9420_TT.webp'),
    capitulos: 6,
fuente: [
      "https://mega.nz/embed/8AsBwSKR#5tSB1mdUx1wZrYAAgLOpKO9AJvB6L6wMCH4nKF9sCiA",
      "https://mega.nz/embed/9R0XkI4S#2qu3LdmddWHHckB04ba1sL61Z1TXHiMV5YO0fdUFECA",
      "https://mega.nz/embed/EQVHjSBC#IE4beu6qjqHikGNxyMD_yx6Usiccp1_3o1eVEIcB7X4",
      "https://mega.nz/embed/1EUlkRSR#3cuV9lyv8m5mMa7fvhs3jjGYKtAeJHNhTlcN5clmw6c",
      "https://mega.nz/embed/gMVR1KBQ#UPG3z3efEmNe0WUTfalesTfA5Aia6i-oHPzXJOPsj1o",
      "https://mega.nz/embed/ZJsSFCZD#FdBeCSqNJAq3vyvHQx7UDMQbWYFMyWCXh1GxchUOxWQ",
    ],

    nombresEpisodios: [
  "Episodio 1",
  "Episodio 2",
  "Episodio 3",
  "Episodio 4",
  "Episodio 5",
  "Episodio 6",
],
    fechaEstreno: '2006',
    puntuacion: 7,
    categoria: ['Serie'],
    verticalbanner: require('../assets/images/170506955_ycasug.jpg')
  },
];