export interface ContentItem {
  nombre: string;
  descripcion: string;
  fondo: any;
  logo: any;
  capitulos: number;
  fuente: any[]; // Puedes tipar mejor si lo necesitas
  nombresEpisodios: string[];
  fechaEstreno: string;
  puntuacion: number;
  categoria?: string[];
  verticalbanner: any;
}

export const ContentData: ContentItem[] = [
  {
    nombre: 'Beck: Mongolian Chop Squad',
    descripcion: 'Beck: Mongolian Chop Squad es un anime que sigue la historia de Yukio "Koyuki" Tanaka, un adolescente que descubre su pasión por la música y se une a una banda llamada Beck. A medida que Koyuki y sus amigos luchan por alcanzar el éxito en la industria musical, enfrentan desafíos personales y profesionales, explorando temas de amistad, perseverancia y el poder transformador de la música.',
    fondo: require('../assets/images/beck_bg.jpg'),
    logo: require('../assets/images/beck_logo.png'),
    capitulos: 26,
    fuente: [
  "https://mega.nz/embed/UeMQlRoR#EwlxBorqdNokJXjM0G2JsHlU9dSa9YwZhjnAG2ArWe0",
  "https://mega.nz/embed/YCUjCYCQ#30OGp2gc0pO5oAzhVE5PnEcuDTSvhmo2OB7t25mI0b4",
  "https://mega.nz/embed/ZHsUgAwC#U3LyAl9O84bl_Ve4B_vbwyDQirr21uA22e6SuHhVa4Q",
  "https://mega.nz/embed/9f8RFTCB#MVTyzGVCLr05Vr_KVVy1QnpOFBKVG7NMqkXprDVKJo8",
  "https://mega.nz/embed/kH8hWLIb#rjzRF9Rcje_OXtSfn7UkwWufxoG5swFkjQqHgtLB6Xg",
  "https://mega.nz/embed/wPd3iTbS#RB1wpl8AjjpfZdL2xv38tLfkCb32EL2QvCMhptVGel4",
  "https://mega.nz/embed/gCs3AKYS#q7SX7XX_3JCQWmAg0aIBl837o-BaXUYUTv6WAKGn9vs",
  "https://mega.nz/embed/BKlQ2LiI#xx4bWEDsMu5WkmV979OouGGAomBfD_bmiTKywJUX6kY",
  "https://mega.nz/embed/1DlUgQDa#Us0IIeVyIM9gsoCdxKvbLDKu-JzrOLOO6v-BCxmlSFQ",
  "https://mega.nz/embed/BHNAmJgC#HwiWl9ylp3d-Iy8-LmxJ0KXLSDHV9KB9KU8ohsXbx-8",
  "https://mega.nz/embed/JaklwB5Z#eiozQWqedA5u3IW1mnxTGwWJxWAFHVnhWlKzA9iNWyQ",
  "https://mega.nz/embed/Zbs1xYiI#QVOFwKO2RJBMcfphtCSgGJ5rWnbzbsQHFjWfWA0vayw",
  "https://mega.nz/embed/5Ts3jIRR#pSS3ni2xyOfIlBDKFp7PcLIZEuwH0R2YRbEK2gW8jSQ",
  "https://mega.nz/embed/1HcGXBJa#0JCGpU9biGfqRw_rRJiX94r1ysR-8APX0ydFJPMeUzg",
  "https://mega.nz/embed/4W0U2TSZ#KcmlcodN8m1q15fTKXV-vrAA9SpXSY69D-TWU8xWris",
  "https://mega.nz/embed/gPcyxYzJ#W6UKRL4RKIe0oNyOPrX5EU55YrhnKHmgjTcy7mUzJW0",
  "https://mega.nz/embed/ZaFlnbiR#q9QmS8asUZwQFPoSzB_DDcZ4O2ttouANcr203sW7eWA",
  "https://mega.nz/embed/gadzESbY#F5KIBN725G90efvg2hFrtFmQmYR4RTh-NYI_lGGDEGw",
  "https://mega.nz/embed/sT8ikSwQ#oZIMeYC0qmq9d7LVqDV-Gu1rQ1AErCQwMBLXyNTGV0I",
  "https://mega.nz/embed/pb0HkJKT#Fv318aTpT7MmqXVrgc7L3Q7nbyYSngezjIS549-GEok",
  "https://mega.nz/embed/0Kcx1YCQ#IiRXePMLImGJ76ZM0XeHxARvrRH8kFUsHMKBNT22hLY",
  "https://mega.nz/embed/cfsllaJY#J0kH_1Nej2s1mTyDdqtyO05ZW7tnSbDGx3-c_wZw-FU",
  "https://mega.nz/embed/BT9HwZCD#Np3q67k593LLofozxzpql1YX7iDW12ShcqCSLUIrAdI",
  "https://mega.nz/embed/EHU2lR5R#oB5cGeOAEvvDPEN83kpGLUKBbXS3o68x3Ma1QmEv_Ec",
  "https://mega.nz/embed/9StmxCiB#Oawy_vpICcmKz1rh8CpLDGOV4JjFbsnd-y19v4_FC1U",
  "https://mega.nz/embed/ETcgEaDB#_Zkmt5eCDUjcfcLQsqRFL10qZTZqdhovnghh0EZHVEk"
],
    nombresEpisodios: [
        "1. El escenario de un chaval de 14 años",
        "2. Sala de conciertos",
        "3. Moon on the water",
        "4. Rasguea la guitarra",
        "5. Beck",
        "6. Hyodo y la Jaguar",
        "7. Lucille",
        "8. Comunicado del instituto",
        "9. Víspera del concierto",
        "10. Face",
        "11. Vacaciones de verano",
        "12. Concierto secreto",
        "13. Ciel Bleu",
        "14. Sueño",
        "15. Vuelta al insti",
        "16. Indies",
        "17. Tres días",
        "18. Leon Sykes",
        "19. Blues",
        "20. Greatful sound",
        "21. Componer música",
        "22. La víspera del festival",
        "23. El festival",
        "24. El tercer escenario",
        "25. Slip Out",
        "26. América"
    ],
    fechaEstreno: '2004-10-07',
    puntuacion: 8.9,
    categoria: ['Anime', 'Serie'],
    verticalbanner:'../assets/images/tlouverticalbanner.jpg',
  },
  {
    nombre: 'The Last of Us',
    descripcion: 'The Last of Us sigue a Joel, un hombre endurecido por la pérdida, que debe escoltar a Ellie, una joven inmune a una infección que ha devastado al mundo. Juntos cruzan un Estados Unidos postapocalíptico lleno de peligros humanos e infectados, enfrentando desafíos que pondrán a prueba su vínculo, su moral y su voluntad de sobrevivir.',
    fondo: require('../assets/images/tloutemp1.webp'),
    logo: require('../assets/images/The_Last_of_Us_logo.png'),
    capitulos: 9,
    fuente: [],
    nombresEpisodios: [
        "1. Cuando te pierdes en la oscuridad",
        "2. Infectados",
        "3. Mucho, mucho tiempo",
        "4. Por favor, toma mi mano",
        "5. Resistir y sobrevivir",
        "6. Familia",
        "7. Lo que dejamos atrás",
        "8. En nuestras horas más bajas",
        "9. Busca la luz"
    ],
    fechaEstreno: '',
    puntuacion: 9.5,
    categoria: ['Serie'],
    verticalbanner: require('../assets/images/tlouverticalbanner.jpg')
  },
  {
    nombre: 'Monster',
    descripcion: 'El doctor Kenzo Tenma es un prometedor neurocirujano japonés que ejerce en el Eisler Memorial Hospital de Dusseldorf. Lo tiene todo en la vida; un trabajo que le apasiona y en el que demuestra una habilidad increíble, y una novia rica y guapa. Sin embargo, un día decide ignorar una orden de su superior y salva a un niño desconocido en lugar de la vida del alcalde de la ciudad.',
    fondo: require('../assets/images/Monster.png'),
    logo: require('../assets/images/Monsterbanner.png'),
    capitulos: 74,
    fuente: [
        "https://mega.nz/embed/OfgE3Azb#AEsgFwDBLFOQAz-trXRumQC_zwsAjuBmkB1vFa1lbIg",
        "https://mega.nz/embed/uCgU2IZQ#ABZkNgAN7RXj0QRNhrR5eQCdStgAMWll4_qJZIaCfh0",
        "https://mega.nz/embed/2LBxzALB#AGf1KgCAxIvAlzYFu4zrdABMv3YAuT-BwNBh07tr2kU",
        "https://mega.nz/embed/eLYUDDDK#AKUz6gCTzvW0eKh4JOGlQQCVwxoAnVDItMJ1UiTh8Po",
        "https://mega.nz/embed/2X5BGbbL#ANEN9ACJGbZF9W9008nGbQDJh9QASoD1RWht1NNoMkA",
        "https://mega.nz/embed/CCxBhbzY#AHDHBACRLQ6MTkq7al6TYwCceYoAk8PojCrpvmrwYkY",
        "https://mega.nz/embed/qHQRESoS#AOe1zwCGablOT-sHxiZ9owC_twUALraJThRwQ8YeLqM",
        "https://mega.nz/embed/OaAzDSLD#ALXXfQDfKyBx8tZfzWO9mwB7FV4AgTEpcXOCHc2lgsg",
        "https://mega.nz/embed/PLgDSCSZ#ANvSvAB2C717nec7HRFAeQBmbYkA7_dMe9Ih9B2f8MM",
        "https://mega.nz/embed/vWByiCyK#AM01_AAeKMkMV9vNkJ_CeQCeTtwAas8tDMwta5BQXJ8",
        "https://mega.nz/embed/DTAE3L7b#AK6g9QDOfOL3OSKYcbkXBgAiZ60ARTUu9xWV83Gmf5A",
        "https://mega.nz/embed/uDgywZYB#ANscxQAMEloWecnZEUKlUwBBTWAA7413FqpZbhGzfoc",
        "https://mega.nz/embed/GD4CATbK#AGINiQATBX9-KQeF71tOTADxrsYAWEblfrUgPO-6uHM",
        "https://mega.nz/embed/qbxUDJIR#AByuywBOjW3kFbOKmpDwEgDZ4kIA3INR5MmKFJr0CEA",
        "https://mega.nz/embed/CD5HlDYS#ADnl5gDfsz6_foxnIO8ODAA9W8QAOeaZv3LnQyAALzE",
        "https://mega.nz/embed/7GwjDTgb#ADG_rABHzHJJD9_ZjO7TjABR7VUA6f6HSUT2y4wWYuY",
        "https://mega.nz/embed/LfBSjagB#AG2EIADUiHTTn539LltC5ACk5z8A02ul0yPkGi4txkY",
        "https://mega.nz/embed/jHQTASSZ#AF4b6QDk2gjmEypzKwHuCwDzpi4A6bDy5hmLoytm4dI",
        "https://mega.nz/embed/2Hw13ShB#AIaqswCqP-eG7WbW4X_U5QDuTtEAmdTuhoWmbeFWFa4",
        "https://mega.nz/embed/mfg3DaiD#APCLMgB1eslPn-mHK7FuTAByInkAT7dhT72RJistQ5c",
        "https://mega.nz/embed/mK5FHIKC#APi3FwABnUF6QciZgMaT8QB82CwA6vTfetE2tYCzJuc",
        "https://mega.nz/embed/eLwxVLJT#AB1IpACcJLsxb3HSV63MTAC-fRsAXLKvMSuPzleZ9IY",
        "https://mega.nz/embed/vG5EVAaK#AG39pABrXu3BlrkWfm4bjABmBVkAR5u_wd0J336xOT4",
        "https://mega.nz/embed/SL5jgaaZ#AGNfLQCOwhfk0e5Nn3vS3gBXwP8ASKjj5JHRJJ_q2Xg",
        "https://mega.nz/embed/KLpWBRZa#AOSD9wA5NSddJrhXEBIVKgBXsGkAPVxnXUiyURB1RG4",
        "https://mega.nz/embed/mGhSybgb#APAPNwBX75gpXFUuThp7_wD1g4QAQWvvKagNsU72MeM",
        "https://mega.nz/embed/qPhEgK4Y#AOW4xwBFmVNrPwKnEBd3-ACz49MAxvQka-oz7xDkGww",
        "https://mega.nz/embed/yHoGFSBA#AJ1ElgAJLMXt6QLTBxVOvwDJ2FQA4lFE7fyDKAe_Dng",
        "https://mega.nz/embed/aLw1XLbA#AKLWkgDzD790EVzePOeuQwB_F4IAgjCEdNJCBDwF3qs",
        "https://mega.nz/embed/bL5R1QjB#AFtM-QCmPJ29ysPkEaJa9wBqZ1UA_SrxvWMiPxGe1b8",
        "https://mega.nz/embed/XZ4EkChB#L90iEbAQUrvpANGMGCzvL-2Vv9OtfPlVK_1gcVK6UMM",
        "https://mega.nz/embed/mGgl0KAC#AJ4ungDlc8g6XkLT_MbCMgBUOHwARnD-OhHKvPxMd48",
        "https://mega.nz/embed/6X4hja6L#AABMqACuo2CmoS48nqElaQCOFJEAfEMXpjfcn57ckbE",
        "https://mega.nz/embed/nGggEAaa#AD30DwAnTpv-2G_i-otMMABNJ-oAWixY_gDCofrejjg",
        "https://mega.nz/embed/CHpTgaTB#AB08qABVdYWQiJjETQuZAgA6mo4A7glYkH5wVU0A34w",
        "https://mega.nz/embed/Xa4hDIqD#AI1JFgCBPOXtDhdE6H_0FwDsSFUA9QRV7Uo7JegGF9Q",
        "https://mega.nz/embed/6WQx0AJZ#AOGuNgCI-fSRcpEvmbMNOQAzOB8AgIGHkR3_jJlYbu0",
        "https://mega.nz/embed/qXx2jZYI#ADjmNwCgL935RIhpWMorVABzBXEA8En--eb5O1jSzng",
        "https://mega.nz/embed/Xb4REKgQ#APTCuwCuZF14JpmPWXSjuQACBsQAQ7rJeISWoVnczKw",
        "https://mega.nz/embed/WCxV0BLS#AHIyOgD_nNCoYyR3w8lKfwAl0rgASBWjqF0bc8MLxGs",
        "https://mega.nz/embed/yK413TiL#AAL7LQDmME2i7QDkt4stwgBOQbQAgYOrosGXpbeUAWM",
        "https://mega.nz/embed/mDImBSYJ#AMvKlAAn4RRB6lVdJUgH3QAKgy0AjlwgQf3HJCWs2yQ",
        "https://mega.nz/embed/jeIWRIza#AHMHNQChxdzRSL-Yr9HUegBEI38Awqlf0c2t06-Y9PU",
        "https://mega.nz/embed/7eYVjazS#AJkQcQAHzFeYT6KFqwB2EwCjsyIAcVykmDF3hasWdF4",
        "https://mega.nz/embed/fWBXjTCK#AFPfwwAtW0vfZcNPyBZx3gDbM6YAAETO3wv0q8iMYYQ",
        "https://mega.nz/embed/EdkW3bSA#tM1W37gO0ZstoBq6wzzsll52rGDIsGV_pYUXufWZIPc",
        "https://mega.nz/embed/2GYRAbjb#AFfk5QDTBPN9sqVj1lDmSQBHDPIAHiktfbf6AtbRXSs",
        "https://mega.nz/embed/XCZg1a7S#AOkCSAD1rOH0-_frBC4OKQCjLLEA-n-X9MQrlgQP73Y",
        "https://mega.nz/embed/qShlRKDT#AIG5TgCUIeX0tf1tYlHXUwAYqUMAXM3k9I3LWWJImVU",
        "https://mega.nz/embed/yP53QLib#ADesuwCKrhwy6Z6sVSxfEAAs5kEAwbIlMjQa9VV_0GE",
        "https://mega.nz/embed/2ToS1S5C#AMCLxAD7DOWWLxu5lP15dgA824MAvrr2ls86dJTZMfs",
        "https://mega.nz/embed/raIkTZ7D#ALeDagDhTEnmUGa4k_KelABwIjcAOKJs5qtHFZNGN5g",
        "https://mega.nz/embed/XX4UVZQL#AOi2-gBPjR3J4Wv3G8RTDgCcCfYAbUxCybUxUxv6dRI",
        "https://mega.nz/embed/TaIRQajQ#AM3KdwC4EignjRsLSuJ3awCWCzoAWR0NJyq02UqOXY8",
        "https://mega.nz/embed/ze5CVSJS#AB_PqQD2B2CEalmSHh899wAVpq8A7YgUhGsurR5DXnY",
        "https://mega.nz/embed/aCBBTDDb#AO2V3wAKTXhCgaqqCiRPwwBc-74AcnlfQiIh-goYhWQ",
        "https://mega.nz/embed/XDgGkZLK#AFJBGQCsrRBbvV9XJy6oPgBW8WYAwE9YW8onIyfq5j4",
        "https://mega.nz/embed/HXRQAJzB#AH6ltgAu6RWUklNIqLoYGgDGhIcA-3D1lLbwGajqAzk",
        "https://mega.nz/embed/ObYVyIbJ#AKBr-QBlrQTL5bul_IRssgDy3yAAFTHly11alfyVpNw",
        "https://mega.nz/embed/6Lp2TBaL#AGFGdQAxzEQBt8YFS8xpBACGj20Axf7vAaAUK0stv6E",
        "https://mega.nz/embed/WfwEmabK#ALjzugBEsZoxEg9z6H4VvQCOAt0A2gfgMZGlKuinxwQ",
        "https://mega.nz/embed/afIiUDAT#AHxaiAD6j7Y8P1Ta0hMojQCi28cA51RZPBe9r9IzhFU",
        "https://mega.nz/embed/DDIljSZa#AIpXsQBwHNIKJE9lJuuJgwCZQLEA5vg-CtTrSibqk2M",
        "https://mega.nz/embed/TLAGVZ4C#AJBlHgA7feL4huVbrXCVBQAnvaMAB9l3-LHc9q1FzxY",
        "https://mega.nz/embed/XLIiyKSD#AI2xeQASpd77mVSZ8pUcTACLcWUAmyHG-9DStfJKhtE",
        "https://mega.nz/embed/uaQXBJSL#AM5HGwAoHNn_LxXOWP_ZkgBxRtMAdTRw_zEOr1ig-Zk",
        "https://mega.nz/embed/PCAQyByZ#ABmb0gBp6jors3CRT_VczADhvfAAZMN4K-MX-U9ZX2o",
        "https://mega.nz/embed/GLxSlIqS#ABY_QgCeqG6fesah_yFbVwDONAsAqY0Xn4SVy__DqOI",
        "https://mega.nz/embed/SCZ0EAhL#AMUAbwDF6DAvLfF590CeLAAh8uIAAI7lL9b5lPdIJhA",
        "https://mega.nz/embed/baIABRLa#AOQURgCFh0Zi8dnDe35tJgBncHAAoZNHYlJFK3vMWP0",
        "https://mega.nz/embed/2WxlXBAa#ADwdTAAjnVcdydhtgHNPUQA0gJYAKpN5HaSfOICqjjQ",
        "https://mega.nz/embed/aPxyXa5D#AKmm6gDMwW-IO79oKFmM5gAfkVUAPGzOiCdoGSgE7JQ",
        "https://mega.nz/embed/vfwlTCbQ#APKe3ABz2Eil0i_hpdscGwBUcwkAuoQXpZNTAqWMo3s",
        "https://mega.nz/embed/DKAyjY5J#ANUolgDxMMtNdxfd7uxsnQD_xmIA6te-Tanbsu5HpQc"
    ],
    nombresEpisodios: [
        "Herr doctor Tenma",
        "Asesinato",
        "La noche de la ejecución",
        "La chica de Heidelberg",
        "Artículos de desapariciones",
        "La mansión de la tragedia",
        "Perseguido",
        "El mercenario y la niña",
        "Borrar el pasado",
        "Kinderheim 511",
        "Un experimento insignificante",
        "Petra y Schuhmann",
        "El último hombre, la última mujer",
        "Be my baby",
        "La confesión de Wolf",
        "Reunión",
        "Cinco cucharadas de azúcar",
        "El abismo del monstruo",
        "Viaje a Freinheim",
        "Unas felices vacaciones",
        "La trampa de Lunge",
        "La confesión de Eva",
        "Alrededor de una mesa",
        "El chico de los jueves",
        "El bosque secreto",
        "La prueba",
        "Un sólo asesino",
        "Ejecución",
        "La decisión",
        "A plena luz del día",
        "Santuario",
        "Escenas de una infancia",
        "El fin de la oscuridad",
        "Un héroe sin nombre",
        "El monstruo que siembra el caos",
        "El monstruo sin nombre",
        "El demonio ante mis ojos",
        "El infierno en sus ojos",
        "Grimmer",
        "El fantasma del 511",
        "Las aventuras de Steiner el magnífico",
        "El detective Suk",
        "Dobles tinieblas",
        "El rastro del monstruo",
        "Ángulo muerto",
        "Las puertas de la pesadilla",
        "Lo que te da más miedo",
        "La crueldad más extrema",
        "La mansión de las rosas",
        "La carta de amor del monstruo",
        "El abogado",
        "La decisión",
        "La huida",
        "La habitación 402",
        "El viaje sin fin",
        "Aquella noche",
        "Odio este trabajo",
        "El hombre que vió al diablo",
        "El hombre que sabía demasiado",
        "La puerta de los recuerdos",
        "Disfrutar la comida",
        "Asesinatos inconexos",
        "La angustia de bebé",
        "Las huellas de Johan",
        "¿Ya has vuelto?",
        "He llegado",
        "Ruhenheim",
        "Un hogar tranquilo",
        "El pueblo de la masacre",
        "La ira de Steiner el magnífico",
        "El hombre sin nombre",
        "El paisaje final",
        "El auténtico monstruo",
        "Degradación"],
    fechaEstreno: '2004',
    puntuacion: 9.2,
    categoria: ['Anime', 'Serie'],
    verticalbanner: require('../assets/images/tlouverticalbanner.jpg')
  }, 
  {
    nombre: 'Devil May Cry',
    descripcion: 'Dante está a cargo de una tienda que hace de todo llamada Devil May Cry. Con un mal carácter y una mala paga hace los trabajos para saldar todas sus deudas. Después de su primera misión ha tenido que quedarse con una niña que según él es insoportable, pero esa niña tiene algo especial, es la heredera de una familia millonaria y de un poder que ni ella conoce.',
    fondo: require('../assets/images/DMC_Banner.png'),
    logo: require('../assets/images/DevilMayCry.png'),
    capitulos: 12,
    fuente: [
  "https://mega.nz/embed/HnAxnAwa#DZWIZwhpcbL8pE4TzcKPUsf2cHRsCDH6_429Ev8-7gY",
  "https://mega.nz/embed/miYzjYZa#hpE3mn78CO2KRjQVHbajEIE9QRE6T4ZNJUkIvBdrUhY",
  "https://mega.nz/embed/vjYh1Kza#LRMiqLgNWHEt52EGC_CKLPak3ochfeNEkTl2g08J9lw",
  "https://mega.nz/embed/f6IhWKpR#e1FyZ5hdWGqoLPIy25PDQlHMMai0x-0BjeMap1sPRgc",
  "https://mega.nz/embed/WyRH1YAK#UIRYlmREkMj0Z5K3VXDd3fGU6TeCBVAZ7DU0nKe0SP4",
  "https://mega.nz/embed/6yBhWICZ#HgXpfhLrPIZ_mMmMlIclzNtkMEwATwJjBUJspmeqeiE",
  "https://mega.nz/embed/2iRzUShZ#kM51LkVribTmU8PxzZf6L2XJqH7PU5x4mhnHN9xcPdA",
  "https://mega.nz/embed/67IRAK6b#9kjybJD4vzb5CcDFSoQWQHFuMLUX9PXCEioZj-SLaYM",
  "https://mega.nz/embed/u7YFyCoB#jfZcSR3RRIySisgjA5tT5DTztcx4clGVGst9C_d26v0",
  "https://mega.nz/embed/HiYVmYJI#H8iaruZNkAXWfKlR56JqWKP1aWsOhz0wjHNnoNDEg_s",
  "https://mega.nz/embed/umZhwIaI#tb0ovvQJCt0tkbLVK1pQGcH-lxS28JJy47Nd2c1FuqM",
  "https://mega.nz/embed/v2QTnYqK#7_Sy-itUoYAiEYyJXjaG-VutnE67aIn49oDMG9GYIFU"
],
    nombresEpisodios: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13"
    ],
    fechaEstreno: '',
    puntuacion: 5.8,
    categoria: ['Anime', 'Serie'],
    verticalbanner: require('../assets/images/tlouverticalbanner.jpg')
  }
];